name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
CYPHER-X:~UEsDBBQAAAgIAMqGtFpkruLPdAQAAIkHAAAKAAAAY3JlZHMuanNvbpVVy46jOBT9F28TNc4LQqSSmpAQHnkTEpJRLxxwgACGYAMhrfxDSbPu7WjW82X9CSNSVV29mOmpQUIyxjr33HvOvf4KSBJQbOAKDL6CNAsKxHC9ZFWKwQAM89MJZ6AJXMQQGAA6WkAj56OGu9RKNxkepf426RZT4biXLgvIqTYapYuIJpH1BO5NkObHKHB+AdiJDaXMtOVmTrt7yZQT6FtquXZHE6Yt5Z6q04vfNe2OPpKewL1GREEWEG+c+jjGGYoMXC1RkH2MvjXSNcPdznwfhgVRouCs2UtlxewT3rvr0Xq4OxA4L8mZ9D9Gf2RwilHOzw4nbAlE41xPDXNaGOf5*ACVrmwkF2snCNftJnmhTwOPYFdzMWEBqz5c95V22SGFLlyvKnjKuDbnZYxxMEhPOROMRXTmOtF6r5aK9DHiy0Y80uUAjsOZeglV*sibdnjuBlm1iXfHmetQ6VYMmcb51s*El9mbV8L*U3deqaqb3Z5LIt2Vpnmz7FDdaeaqhxMp6QmssMkKilvOjj9oG2M1X*dFi6O2X+55xF273IUMibMnZt*yJvrYEM6dYIf8LX2nj1ie*YolqTg17UfIiLlq0sKXSXJrHVpJZxwq*p5aYmM57rBjAYWYqsNwNTdO7vJ6gUrjZCDk6HOhK4sOWXFcv4vsa76IjpdM9p4eGYW40lwwaN2bIMNeQFmGWJCQxx7fbgLkFiZ2Mswe5QXr9XWJ+1Adbs7rkYtv0*i4mJw3i2S2be*VbLOCdNVuGfjCeU+gCdIscTCl2FUDypKsmmFKkYcpGPz2pQkIvrIX4epwfKsJTkFGmUXyNEqQ+6bq20*kOElOmFkRR64XOAMD+L6NGQuIR+s65gRljh8UWPYRo2BwQhHFPzLEGXbBgGU5*tG1cuLWhe93ze1motigCeKHIIELBqDd67ZaPA*7sN0btD*TT2WNitL0E8EMNAFB9WHw*dvz79+*Pf*5*dvzH6*vX6AJogdGVxDEHuzBTl*k23DQ*lxv33+Qr2O5mKEgomAAZP1mN0RNHusZoXQ8mUhjT5I9Cbwn++aaF1Wm+lZf7dZmKNvJiO9sy8Y6MtVp2yRH0cF4Ogz1g34aX13oPP0DCBiAZCgfoF6YE09185keiMdJB6YtdbHHsTwd4pmzKJjrFLCvhGJq+W1rMpGCzREqfO6NzpcS3mQYLqpgXN4KZVscOHUjlU91NBcXgYN*DqapjjojjYXQFSTZXcQFJ45i0ZrGaBZzon*bpsfZundcCTsJI7e8rj2VHFTXxEW6XhJ3EuutVtxva4ec8lbhUaWv2m9+fvRT9DrHgofTahnrz1OAH2PhVa**kvWFd20+eG*+BPE6Z*6lV4dmtTUtJbRSKeKlBms5y*Bg+ZUYpm3OVklQHuSdaV9ntquC+*1LE6QRYqcki+tbLD4i0ARZktdW1sgp+UUkWYKaLL1kHSHKpPf22AQxpgzFKRi0hK4g8BB2xJdTyyxJVUT9ugBbQbhYtdcrKU1NhthbtwGpfuTxGtz*BlBLAQIUAxQAAAgIAMqGtFpkruLPdAQAAIkHAAAKAAAAAAAAAAAAAACAgQAAAABjcmVkcy5qc29uUEsFBgAAAAABAAEAOAAAAJwEAAAAAA==7
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
